version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "32380:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: GameDB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
